spring:
  application:
    name: ratingus-backend
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 5000

jwt:
  secret: ${TOKEN_KEY}
  expiration: 1800000