---

- name: Update Docker Compose containers
  hosts: ratingus
  gather_facts: no
  become: yes

  tasks:
    - name: Update Docker Compose containers
      community.docker.docker_compose_v2_pull:
        project_src: "{{ project_src }}"
      register: output


    - name: Stop all services
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        state: stopped
      register: output

    - name: Restart services
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        state: restarted
      register: output
