---

- name: Update Docker Compose containers
  hosts: ratingus
  gather_facts: no
  become: yes

  tasks:
    - name: Install docker-compose python package
      ansible.builtin.pip:
        name: docker-compose

    - name: "stop services"
      shell: docker-compose -f {{ project_src }}/compose.yml stop

    - name: "pull images"
      shell: docker-compose -f {{ project_src }}/compose.yml pull

    - name: "start services"
      shell: docker-compose -f {{ project_src }}/compose.yml up -d
