name: Update Docker Containers and Deploy

on:
  push:
    branches:
      - dnlkk/cicd

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ratingus-backend .
          docker push ghcr.io/${{ github.repository_owner }}/ratingus-backend

      - name: Print working directory
        run: echo $GITHUB_WORKSPACE


      - name: Update Docker Compose containers on server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: update_stand.yml
          directory: production/
          inventory: |
            [all]
            ${{ secrets.SERVER_IP }}
          extra_vars: |
            project_src=${{ secrets.PROJECT_SRC_PATH }}
            server_ip=${{ secrets.SERVER_IP }}
          become: yes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
