name: Update Docker Containers and Deploy

on:
  push:
    branches:
      - dnlkk/cicd

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure ~/.ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Start SSH agent
        run: ssh-agent -s > ~/.ssh/ssh-agent.env

      - name: Load SSH agent environment variables
        run: source ~/.ssh/ssh-agent.env

      - name: Add SSH private key to agent
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ratingus-backend .
          docker push ghcr.io/${{ github.repository_owner }}/ratingus-backend


      - name: Update Docker Compose containers on server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: update_stand.yml
          directory: production/
          username: ${{ secrets.SERVER_USERNAME }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          inventory: |
            [all]
            ${{ secrets.SERVER_IP }}
          options: |
            -e project_src=${{ secrets.PROJECT_SRC_PATH }}
            -e server_ip=${{ secrets.SERVER_IP }}
